name: Build and Push Image to Dockerhub and GHCR

on:
  push:
    branches: ["main"]
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: "${{ secrets.DH_USER }}"
      #     password: "${{ secrets.DH_PASS }}"
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: "hargata"
      #     password: "${{ secrets.GHCR_PAT }}"
      - name: Generate Tag from Release
        id: releaseh_tag
        if: github.event.release
        run: echo "IMAGE_TAG=$(echo ${{ github.event.release.tag_name }})"
      - name: Generate Tag from Branch
        id: branch_tag
        if: github.event_name == 'push'
        run: echo "IMAGE_TAG=main"
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       hargata/lubelogger:${{ env.IMAGE_TAG }}
      #       ghcr.io/hargata/lubelogger:${{ env.IMAGE_TAG }}
